CREATE TABLE IF NOT EXISTS TB_WEBHOOK_CONFIG (
    id INT NOT NULL AUTO_INCREMENT,
    webhook_url VARCHAR(2000) NOT NULL,
    active_yn TINYINT NOT NULL DEFAULT 1,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);
